// attributes: bloodlust, magicform, weakness
// sans can beat someone with bloodlust but not magicform
// dr. strange can beat someone with magicform
// batman can beat someone with a weakness

everything = [["Abraham Lincoln", "images/abe.jpg", 0, "none"],
              ["Barrack Obama", "images/obama.jpg", 0, "none"],
              ["Hillary Clinton", "images/clinton.jpg", 0, "none"],
              ["Donald Trump", "images/donald_trump.jpg", 0, "none"],
              ["Justin Bieber", "images/justin_bieber.jpg", 0, "none"],
              ["Teletubbies Sun", "images/teletubbies_sun.jpg", 0, "magicform"],
              ["Bambi", "images/bambi.png", 0, "none"],
              ["Elsa", "images/elsa.png", 0, ""],
              ["Goofy", "images/goofy.png", 0, "none"],
              ["Donald Duck", "images/donald_duck.png", 0, "none"],
              ["Godzilla", "images/godzilla.jpg", 0, "none"],
              ["Goku", "images/goku.png", 0, "none"],
              ["Vegeta", "images/vegeta.png", 0, "none"],
              ["Gogeta", "images/gogeta.png", 0, "none"],
              ["Majin Buu", "images/majin_buu.png", 0, "bloodlust"],
              ["Naruto", "images/naruto.png", 0, "none"],
              ["Sasuke", "images/sasuke.png", 0, "none"],
              ["Sailor Moon", "images/sailor_moon.jpg", 0, "none"],
              ["Mario", "images/mario.png", 0, "none"],
              ["Luigi", "images/luigi.jpg", 0, "weakness"],
              ["Peach", "images/peach.png", 0, "none"],
              ["Rosalina", "images/rosalina.png", 0, "none"],
              ["Link", "images/link.png", 0, "none"],
              ["Zelda", "images/zelda.png", 0, "none"],
              ["Samus", "images/samus.jpg", 0, "none"],
              ["Sonic the Hedgehog", "images/sonic.jpg", 0, "none"],
              ["Shadow the Hedgehog", "images/shadow.png", 0, "none"],
              ["Mega Man", "images/mega_man.png", 0, "none"],
              ["Chun Li", "images/chun_li.png", 0, "none"],
              ["Cloud", "images/cloud.png", 0, "none"],
              ["Sephiroth", "images/sephiroth.png", 0, "bloodlust"],
              ["Sora", "images/sora.png", 0, "none"],
              ["Finn", "images/finn.png", 0, "none"],
              ["Princess Bubblegum", "images/princess_bubblegum.png", 0, "none"],
              ["Marceline", "images/marceline.jpg", 0, "none"],
              ["Bill Cipher", "images/bill_cipher.jpg", 0, "magicform"],
              ["Superman", "images/superman.jpg", 0, "weakness"],
              ["Batman", "images/batman.png", 0, "none"],
              ["The Joker", "images/joker.jpg", 0, "none"],
              ["Wonder Woman", "images/wonder_woman.jpg", 0, "weakness"],
              ["The Flash", "images/flash.jpg", 0, "weakness"],
              ["Dr. Manhattan", "images/manhattan.png", 0, "none"],
              ["Luke Skywalker", "images/luke_skywalker.png", 0, "none"],
              ["Rey", "images/rey.png", 0, "weakness"],
              ["Darth Vader", "images/darth_vader.png", 0, "bloodlust"],
              ["Harry Potter", "images/harry_potter.jpg", 0, "none"],
              ["Hermione", "images/hermione.jpg", 0, "none"],
              ["Voldemort", "images/voldemort.jpg", 0, "bloodlust"],
              ["Sauron", "images/sauron.jpg", 0, "magicform"],
              ["Master Chief", "images/master_chief.png", 0, "none"],
              ["Spider Man", "images/spider_man.png", 0, "none"],
              ["The Hulk", "images/hulk.jpg", 0, "weakness"],
              ["Iron Man", "images/iron_man.jpg", 0, "weakness"],
              ["Thor", "images/thor.png", 0, "none"],
              ["Loki", "images/loki.jpg", 0, "bloodlust"],
              ["Captain America", "images/captain_america.png", 0, "none"],
              ["Wolverine", "images/wolverine.jpg", 0, "none"],
              ["Storm", "images/storm.png", 0, "none"],
              ["Doctor Strange", "images/doctor_strange.jpg", 0, "none"],
              ["Shrek", "images/shrek.png", 0, "none"],
              ["Homer Simpson", "images/homer.jpg", 0, "none"],
              ["sans", "images/sans.jpg", 1, "magicform"],
              ["Papyrus", "images/papyrus.png", 20, "magicform"],
              ["Toriel", "images/papyrus.png", 80, "magicform"],
              ["Undyne", "images/undyne.png", 50, "magicform"],
              ["Asgore", "images/asgore.png", 80, "magicform"],
              ["Flowey", "images/flowey.jpg", 3, "bloodlust"],
              ["Chara", "images/chara.png", 99, "bloodlust"]]

// character: image, name, number, attribute
// if character > other character:
// show accurate symbol between
// else:
// they're tied